# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
    - name: Check repository
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.15
        
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Run build
      run: go build cmd/web/*.go
      
    # Run vet & lint on the code
#     - name: Run vet & lint
#       run: |
#         go vet cmd/web/
#         golint cmd/web/
      
    # Run testing on the code
#     - name: Run testing
#       run: cd test && go test -v
    
  deploy:
    
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cr.yandex/crp1kafuq6umi5ce3tra/okc46go:latest
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} cr.yandex
        docker push cr.yandex/crp1kafuq6umi5ce3tra/okc46go:latest

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo -n docker-compose -f /opt/docker/docker-compose.yml pull okc46go
         # sudo -n docker-compose -f /opt/docker/docker-compose.yml stop okc46go
         # sudo -n docker-compose -f /opt/docker/docker-compose.yml up -d okc46go
